ProjectAgileWeb7/Controllers/AdminHotelsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectAgileWeb7.Data;
using ProjectAgileWeb7.Models;

namespace ProjectAgileWeb7.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminHotelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AdminHotelsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Hotels.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .FirstOrDefaultAsync(m => m.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HotelId,Name,Website,Address,ZipCode,City,Country,Description,Stars,DistanceFromCenter,Latitude,Longitude,ImageUrl,RatedByGuests")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var fileName = Guid.NewGuid().ToString();
                var folder = Path.Combine(webRootPath, @"pictures");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(folder, fileName + extension), FileMode.Create))
                {
                    await files[0].CopyToAsync(fileStream);
                }
                hotel.ImageUrl = @"~/pictures/" + fileName + extension;

                _context.Add(hotel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels.FindAsync(id);
            if (hotel == null)
            {
                return NotFound();
            }
            return View(hotel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HotelId,Name,Website,Address,ZipCode,City,Country,Description,Stars,DistanceFromCenter,Latitude,Longitude,ImageUrl,RatedByGuests")] Hotel hotel)
        {
            if (id != hotel.HotelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var webRootPath = _webHostEnvironment.WebRootPath;
                    var files = HttpContext.Request.Form.Files;
                    if (files.Count > 0)
                    {
                        var fileName = Guid.NewGuid().ToString();
                        var folder = Path.Combine(webRootPath, @"pictures");
                        var extension = Path.GetExtension(files[0].FileName);

                        using (var fileStream = new FileStream(Path.Combine(folder, fileName + extension), FileMode.Create))
                        {
                            await files[0].CopyToAsync(fileStream);
                        }
                        hotel.ImageUrl = @"~/pictures/" + fileName + extension;
                    }
                    else
                    {
                        hotel.ImageUrl = _context.Hotels.Where(h => h.HotelId == hotel.HotelId)
                            .Select(h => h.ImageUrl)
                            .FirstOrDefault();
                    }

                    _context.Update(hotel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HotelExists(hotel.HotelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hotel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hotel = await _context.Hotels
                .FirstOrDefaultAsync(m => m.HotelId == id);
            if (hotel == null)
            {
                return NotFound();
            }

            return View(hotel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hotel = await _context.Hotels.FindAsync(id);
            _context.Hotels.Remove(hotel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HotelExists(int id)
        {
            return _context.Hotels.Any(e => e.HotelId == id);
        }
    }
}

ProjectAgileWeb7/Controllers/AdminRoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectAgileWeb7.Data;
using ProjectAgileWeb7.Models;

namespace ProjectAgileWeb7.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminRoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminRoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {
            var applicationDbContext = _context.Rooms.Include(r => r.Hotel);

            if (id != null)
            {
                applicationDbContext = _context.Rooms.Where(r => r.HotelId == id).Include(r => r.Hotel);
            }

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Hotel)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        public IActionResult Create()
        {
            ViewData["HotelId"] = new SelectList(_context.Hotels, "HotelId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomId,RoomType,RoomNumber,RoomPrice,RoomDescription,NumberOfBeds,Capacity,IsAvailable,RoomImageUrl,HotelId")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "HotelId", "HotelId", room.HotelId);
            return View(room);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "HotelId", "Name", room.HotelId);
            return View(room);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomId,RoomType,RoomNumber,RoomPrice,RoomDescription,NumberOfBeds,Capacity,IsAvailable,RoomImageUrl,HotelId")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.RoomId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HotelId"] = new SelectList(_context.Hotels, "HotelId", "HotelId", room.HotelId);
            return View(room);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Hotel)
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.RoomId == id);
        }
    }
}

ProjectAgileWeb7/Views/AdminRooms/Create.cshtml
@model ProjectAgileWeb7.Models.Room

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-lg-right">
    <a asp-action="Index" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to List</a>
</div>

<h3 class="text-success"><i class="fas fa-plus-circle"></i>&nbsp; Add New Room</h3>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomType" class="control-label"></label>
                <select asp-for="RoomType" asp-items="Html.GetEnumSelectList<RoomType>()" class="form-control"></select>
                <span asp-validation-for="RoomType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomPrice" class="control-label"></label>
                <input asp-for="RoomPrice" class="form-control" />
                <span asp-validation-for="RoomPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomDescription" class="control-label"></label>
                <textarea asp-for="RoomDescription" class="form-control"></textarea>
                <span asp-validation-for="RoomDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfBeds" class="control-label"></label>
                <input asp-for="NumberOfBeds" class="form-control" />
                <span asp-validation-for="NumberOfBeds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Room image</label>
                <select asp-for="RoomImageUrl" class="form-control">
                    <option>~/pictures/single.jpg</option>
                    <option>~/pictures/double.jpg</option>
                    <option>~/pictures/triple.jpg</option>
                    <option>~/pictures/twin.jpg</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Hotel" class="control-label"></label>
                <select asp-for="HotelId" class ="form-control" asp-items="ViewBag.HotelId"></select>
            </div>
            <input type="submit" value="Add Hotel Room to Database" class="btn btn-success" />
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectAgileWeb7/Views/AdminRooms/Delete.cshtml
@model ProjectAgileWeb7.Models.Room

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-lg-right">
    <a asp-action="Index" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to List</a>
</div>

<h3 class="text-danger"><i class="fas fa-trash-alt"></i>&nbsp; Room Id: @Model.RoomId</h3>

<h4>Are you sure you want to delete this room?</h4>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfBeds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBeds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomImageUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hotel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hotel.HotelId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hotel.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hotel.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoomId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

ProjectAgileWeb7/Views/AdminRooms/Details.cshtml
@model ProjectAgileWeb7.Models.Room

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-lg-right">
    <a asp-action="Index" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to List</a>
    <a asp-action="Edit" asp-route-id="@Model.RoomId" class="btn btn-outline-warning btn-sm"><i class="fas fa-edit"></i>&nbsp; Edit</a>
</div>
<h3 class="text-info"><i class="fas fa-info-circle"></i>&nbsp; Room Id: @Model.RoomId</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfBeds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumberOfBeds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RoomImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RoomImageUrl)
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content(Model.RoomImageUrl)" width="200" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hotel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hotel.HotelId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hotel.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hotel.Name) &nbsp;
            <a asp-action="Details" asp-controller="AdminHotels" asp-route-id="@Model.HotelId" class="btn btn-sm btn-outline-info">Show Hotel Details</a>
        </dd>
    </dl>
</div>

ProjectAgileWeb7/Views/AdminRooms/Edit.cshtml
@model ProjectAgileWeb7.Models.Room

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-lg-right">
    <a asp-action="Index" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to List</a>
</div>

<h3 class="text-warning"><i class="fas fa-edit"></i>&nbsp; Room Id: @Model.RoomId</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoomId" />
            <div class="form-group">
                <label asp-for="RoomType" class="control-label"></label>
                <select asp-for="RoomType" asp-items="Html.GetEnumSelectList<RoomType>()" class="form-control"></select>
                <span asp-validation-for="RoomType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomPrice" class="control-label"></label>
                <input asp-for="RoomPrice" class="form-control" />
                <span asp-validation-for="RoomPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomDescription" class="control-label"></label>
                <textarea asp-for="RoomDescription" class="form-control"></textarea>
                <span asp-validation-for="RoomDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfBeds" class="control-label"></label>
                <input asp-for="NumberOfBeds" class="form-control" />
                <span asp-validation-for="NumberOfBeds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Room image</label>
                <select asp-for="RoomImageUrl" class="form-control">
                    <option>~/pictures/single.jpg</option>
                    <option>~/pictures/double.jpg</option>
                    <option>~/pictures/triple.jpg</option>
                    <option>~/pictures/twin.jpg</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Hotel" class="control-label"></label>
                <select asp-for="HotelId" class="form-control" asp-items="ViewBag.HotelId"></select>
                <span asp-validation-for="HotelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectAgileWeb7/Views/AdminRooms/Index.cshtml
@model IEnumerable<ProjectAgileWeb7.Models.Room>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="float-lg-right">
    <a asp-action="Create" class="btn btn-success"><i class="fas fa-plus-circle"></i>&nbsp; Add New Room</a>
    <a asp-area="Identity" asp-page="/Account/Manage/Index" class="btn btn-outline-primary"><i class="fas fa-arrow-alt-circle-left"></i>&nbsp; Back to Profile</a>
</div>

<h1>Rooms</h1>

<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th class="mobile-toggle">
                    @Html.DisplayNameFor(model => model.RoomId)
                </th>
                <th>
                    Type
                </th>
                <th class="mobile-toggle">
                    @Html.DisplayNameFor(model => model.RoomPrice)
                </th>
                <th class="mobile-toggle">
                    @Html.DisplayNameFor(model => model.NumberOfBeds)
                </th>
                <th class="mobile-toggle">
                    @Html.DisplayNameFor(model => model.Capacity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hotel.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th class="mobile-toggle">
                        @Html.DisplayFor(modelItem => item.RoomId)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoomType)
                    </td>
                    <td class="mobile-toggle">
                        @Html.DisplayFor(modelItem => item.RoomPrice)
                    </td>
                    <td class="mobile-toggle">
                        @Html.DisplayFor(modelItem => item.NumberOfBeds)
                    </td>
                    <td class="mobile-toggle">
                        @Html.DisplayFor(modelItem => item.Capacity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hotel.Name)
                    </td>
                    <td class="btn-group mobile-toggle">
                        <a asp-action="Edit" asp-route-id="@item.RoomId" class="btn btn-outline-warning"><i class="fas fa-edit"></i>&nbsp; Edit</a>
                        <a asp-action="Details" asp-route-id="@item.RoomId" class="btn btn-outline-info ml-1"><i class="fas fa-info-circle"></i>&nbsp; Details</a>
                        <a asp-action="Delete" asp-route-id="@item.RoomId" class="btn btn-outline-danger ml-1"><i class="fas fa-trash-alt"></i>&nbsp; Delete</a>
                    </td>
                    <td class="btn-group button-group-icons">
                        <a asp-action="Edit" asp-route-id="@item.RoomId" class="btn btn-outline-warning"><i class="fas fa-edit"></i></a>
                        <a asp-action="Details" asp-route-id="@item.RoomId" class="btn btn-outline-info ml-1"><i class="fas fa-info-circle"></i></a>
                        <a asp-action="Delete" asp-route-id="@item.RoomId" class="btn btn-outline-danger ml-1"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>